### ISSUE TITLE
Parse String

### ISSUE THREAD

**Issue by Licomix** [FlacSy/FLK#1]
If there is a dash in a string, an error is displayed when parsing this string and getting the value. 
Traceback (most recent call last):
  File "...\tests\fltest.py", line 5, in <module>
    parser.parse_file('tests/insta.fl')
  File "...\flk\parser.py", line 405, in parse_file
    self.parse_line(multiline_buffer)
  File "...\flk\parser.py", line 243, in parse_line
    parsed_value = self.evaluate_expression(val
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\flk\parser.py", line 225, in evaluate_expression
    return round(eval(''.join(result)), 5)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1
    C8E-76OoE15
    SyntaxError: invalid decimal literal
    
![ef9a95f2943ea56f86f42c6b9692b685](https://github.com/FlacSy/FLK/assets/59695075/fa01191f-dfd4-4371-81f6-a47e0fe8ab05)

**Comment by FlacSy** [comment]
Пожалуйста  прикрепите файл .fl и ваш код для воспроизведения бага

**Comment by FlacSy** [comment]
# 1.2.2 - String Fix 
#### Уже все работает, пожалуйста обновите [библиотеку к версии 1.2.2](https://pypi.org/project/flk/1.2.2/)
